version: '2'
services:
  server:
    build: .
    volumes:
       - /prog-repos/v1-sd-nginxproxy/var-www-html:/var/www/html
       - /prog-repos/v1-sd-nginxproxy/:/prog-repos/v1-sd-nginxproxy/
       - /prog-repos/v1-sd-nginxproxy/var-log-nginx/:/var/log/nginx/
       - /prog-repos/v1-sd-nginxproxy/etc-supervisor-conf.d-services.conf:/etc/supervisor/conf.d/services.conf
       - /prog-repos/v1-sd-nginxproxy/etc-supervisor-supervisord.conf:/etc/supervisor/supervisord.conf            # this is to disable logging during production
       - /prog-repos/v1-sd-nginxproxy/etc-nginx-sites-enabled-default:/etc/nginx/sites-enabled/default
       - /prog-repos/v1-sd-nginxproxy/etc-nginx-snippets-fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    ports:
       - 80:80
    networks:
       - agni
    restart: unless-stopped

networks:
  emr:
    external:
      name: agni_default